---
- hosts: buildhost[0]
  roles:
    - rg-client-build

- hosts: rosen
  vars_files:
    - vars/rose.yml
  vars: 
    targetdir: /srv/rose
    clientdir: /srv/rose-client
  roles:
    - { role: rg-client-app, when: masternode is defined and masternode }
    - rg-server-app
  tasks:
    - apt:
        name: vim
        state: present
